In [ ]:
#Import required libraries
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

print("TensorFlow version:", tf.__version__)


TensorFlow version: 2.19.0


In [ ]:
corpus = [
"machine learning is the future of technology",
"deep learning helps in image recognition",
"natural language processing is very useful",
"artificial intelligence is transforming industries",
"data science is important for decision making",
"python is widely used in machine learning",
"neural networks learn patterns from data",
"lstm is used for sequence prediction",
"rnn works well with text data",
"ai is used in healthcare and finance",
"big data helps companies grow",
"technology is changing the world",
"students are learning artificial intelligence",
"cloud computing supports big data",
"deep learning models need more data",
"tensorflow is a popular framework",
"pytorch is also widely used",
"data analysis requires clean data",
"machine learning models need training",
"algorithms learn from examples",
"text generation is done using lstm",
"sequence models predict next word",
"ai is the future of innovation",
"automation is increasing in industries",
"robots are powered by ai",
"data engineers manage pipelines",
"data analysts create reports",
"neural networks have many layers",
"deep learning improves accuracy",
"training data is very important",
"prediction models require testing",
"lstm remembers past information",
"rnn has memory capability",
"artificial intelligence helps humans",
"technology makes life easier",
"students study data science",
"programming is essential for ai",
"python is easy to learn",
"learning never stops in technology",
"innovation drives the future"
]

print("Number of sentences:", len(corpus))
print("\nSample corpus:")
for line in corpus:
    print("-", line)


Number of sentences: 40

Sample corpus:
- machine learning is the future of technology
- deep learning helps in image recognition
- natural language processing is very useful
- artificial intelligence is transforming industries
- data science is important for decision making
- python is widely used in machine learning
- neural networks learn patterns from data
- lstm is used for sequence prediction
- rnn works well with text data
- ai is used in healthcare and finance
- big data helps companies grow
- technology is changing the world
- students are learning artificial intelligence
- cloud computing supports big data
- deep learning models need more data
- tensorflow is a popular framework
- pytorch is also widely used
- data analysis requires clean data
- machine learning models need training
- algorithms learn from examples
- text generation is done using lstm
- sequence models predict next word
- ai is the future of innovation
- automation is increasing in industries
- robots are pow

In [ ]:
#Tokenization
#it completes the setences
tokenizer = Tokenizer()
tokenizer.fit_on_texts(corpus)

word_index = tokenizer.word_index
total_words = len(word_index) + 1  # +1 because indexing starts from 1

print("Vocabulary size:", total_words)
print("\nWord index:")
print(word_index)


Vocabulary size: 33

Word index:
{'is': 1, 'learning': 2, 'deep': 3, 'machine': 4, 'learn': 5, 'data': 6, 'powerful': 7, 'fun': 8, 'interesting': 9, 'artificial': 10, 'intelligence': 11, 'the': 12, 'future': 13, 'i': 14, 'love': 15, 'lstm': 16, 'used': 17, 'for': 18, 'sequence': 19, 'prediction': 20, 'neural': 21, 'networks': 22, 'patterns': 23, 'science': 24, 'exciting': 25, 'python': 26, 'easy': 27, 'to': 28, 'models': 29, 'improve': 30, 'with': 31, 'more': 32}


In [ ]:
input_sequences = []

for line in corpus:
    token_list = tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(token_list)):
        n_gram_seq = token_list[:i+1]
        input_sequences.append(n_gram_seq)

print("Total training sequences:", len(input_sequences))
print("\nSome sequences before padding:")
for seq in input_sequences[:10]:
    print(seq)


Total training sequences: 35

Some sequences before padding:
[3, 2]
[3, 2, 1]
[3, 2, 1, 7]
[3, 2]
[3, 2, 1]
[3, 2, 1, 8]
[4, 2]
[4, 2, 1]
[4, 2, 1, 9]
[10, 11]


In [ ]:
max_seq_len = max(len(seq) for seq in input_sequences)
input_sequences = pad_sequences(input_sequences, maxlen=max_seq_len, padding='pre')

print("Maximum sequence length:", max_seq_len)
print("\nPadded sequences:")
print(input_sequences[:10])


Maximum sequence length: 6

Padded sequences:
[[ 0  0  0  0  3  2]
 [ 0  0  0  3  2  1]
 [ 0  0  3  2  1  7]
 [ 0  0  0  0  3  2]
 [ 0  0  0  3  2  1]
 [ 0  0  3  2  1  8]
 [ 0  0  0  0  4  2]
 [ 0  0  0  4  2  1]
 [ 0  0  4  2  1  9]
 [ 0  0  0  0 10 11]]


In [ ]:
X = input_sequences[:, :-1]
y = input_sequences[:, -1]

y = tf.keras.utils.to_categorical(y, num_classes=total_words)

print("Shape of X:", X.shape)
print("Shape of y:", y.shape)


Shape of X: (35, 5)
Shape of y: (35, 33)


In [ ]:
model = Sequential([
    Embedding(input_dim=total_words, output_dim=10, input_length=max_seq_len - 1),
    LSTM(100),
    Dense(total_words, activation='softmax')
])

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
history = model.fit(X, y, epochs=300, verbose=1)

Epoch 1/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7714 - loss: 0.6781
Epoch 2/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.8000 - loss: 0.6711
Epoch 3/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.8286 - loss: 0.6734
Epoch 4/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.8286 - loss: 0.6752
Epoch 5/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8000 - loss: 0.6710
Epoch 6/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7714 - loss: 0.6661
Epoch 7/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7714 - loss: 0.6619
Epoch 8/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7429 - loss: 0.6582
Epoch 9/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7429 - loss: 0.6557
Epoch 10/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7429 - loss: 0.6500
Epoch 11/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7714 - loss: 0.6463
Epoch 12/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8000 - lo

In [ ]:
print("Final Accuracy:", history.history['accuracy'][-1])

Final Accuracy: 0.9714285731315613


In [ ]:
def generate_text(seed_text, next_words):
    for _ in range(next_words):
        token_list = tokenizer.texts_to_sequences([seed_text])[0]
        token_list = pad_sequences([token_list], maxlen=max_seq_len - 1, padding='pre')

        predicted_probs = model.predict(token_list, verbose=0)
        predicted_index = np.argmax(predicted_probs, axis=-1)[0]

        output_word = ""
        for word, index in tokenizer.word_index.items():
            if index == predicted_index:
                output_word = word
                break

        seed_text += " " + output_word
    return seed_text


In [ ]:
print(generate_text("deep learning", 2))
print(generate_text("machine learning", 2))
print(generate_text("python is", 2))
print(generate_text("artificial intelligence", 2))
print(generate_text("data science", 2))
print(generate_text("neural networks", 2))

deep learning interesting used
machine learning interesting used
python is sequence powerful
artificial intelligence machine machine
data science used easy
neural networks used easy
